services:
  postgres:
    container_name: postgres
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
#   volumes:
#     - postgres:/var/lib/postgresql/data
  backend:
    container_name: backend
    build: "."
    ports: 
      - "9001:9001"
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    depends_on:
      - postgres

  frontend:
    container_name: frontend
    build: "./frontend"
    ports: 
      - "3000:3000"
    depends_on:
      - backend


#
#volumes:
#    postgres: {}
