name: GitHub Actions Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    runs-on: my-runner
    steps:
    - uses: actions/checkout@v4
    - name: build the docker image and deploy the containers on local runner.
      run: docker-compose up

