name: GitHub Actions Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    # runs-on: my-runner
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: sudo ls
    # - name: build the docker image and deploy the containers on local runner.
    #   run: docker-compose up

